/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as DiffsRouteRouteImport } from './routes/diffs/route'
import { Route as DiagSplatRouteImport } from './routes/diag/$'
import { Route as DiffsIndexRouteImport } from './routes/diffs/index'
import { Route as DiffsSplatRouteImport } from './routes/diffs/$'
import { Route as ApiDiffsDiffRouteImport } from './routes/api/diffs/diff'
import { Route as ApiDiffsEntityDiffRouteImport } from './routes/api/diffs/entity-diff'
import { Route as ApiDiffsGithubDiffFileRouteImport } from './routes/api/diffs/github-diff-file'
import { Route as ApiDiffsPullRequestsRouteImport } from './routes/api/diffs/pull-requests'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github/callback'
import { Route as ApiAuthGithubConfigRouteImport } from './routes/api/auth/github/config'
import { Route as ApiAuthGithubInstallationsRouteImport } from './routes/api/auth/github/installations'
import { Route as ApiAuthGithubLoginRouteImport } from './routes/api/auth/github/login'
import { Route as ApiAuthGithubLogoutRouteImport } from './routes/api/auth/github/logout'
import { Route as ApiAuthGithubPreviewAuthorizeRouteImport } from './routes/api/auth/github/preview-authorize'
import { Route as ApiAuthGithubPreviewCallbackRouteImport } from './routes/api/auth/github/preview-callback'
import { Route as ApiAuthGithubPreviewRedeemRouteImport } from './routes/api/auth/github/preview-redeem'
import { Route as ApiAuthGithubPreviewStartRouteImport } from './routes/api/auth/github/preview-start'
import { Route as ApiAuthGithubSessionRouteImport } from './routes/api/auth/github/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffsRouteRoute = DiffsRouteRouteImport.update({
  id: '/diffs',
  path: '/diffs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagSplatRoute = DiagSplatRouteImport.update({
  id: '/diag/$',
  path: '/diag/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffsIndexRoute = DiffsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiffsRouteRoute,
} as any)
const DiffsSplatRoute = DiffsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DiffsRouteRoute,
} as any)
const ApiDiffsDiffRoute = ApiDiffsDiffRouteImport.update({
  id: '/api/diffs/diff',
  path: '/api/diffs/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffsEntityDiffRoute = ApiDiffsEntityDiffRouteImport.update({
  id: '/api/diffs/entity-diff',
  path: '/api/diffs/entity-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffsGithubDiffFileRoute = ApiDiffsGithubDiffFileRouteImport.update({
  id: '/api/diffs/github-diff-file',
  path: '/api/diffs/github-diff-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffsPullRequestsRoute = ApiDiffsPullRequestsRouteImport.update({
  id: '/api/diffs/pull-requests',
  path: '/api/diffs/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/api/auth/github/callback',
  path: '/api/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubConfigRoute = ApiAuthGithubConfigRouteImport.update({
  id: '/api/auth/github/config',
  path: '/api/auth/github/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubInstallationsRoute =
  ApiAuthGithubInstallationsRouteImport.update({
    id: '/api/auth/github/installations',
    path: '/api/auth/github/installations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGithubLoginRoute = ApiAuthGithubLoginRouteImport.update({
  id: '/api/auth/github/login',
  path: '/api/auth/github/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubLogoutRoute = ApiAuthGithubLogoutRouteImport.update({
  id: '/api/auth/github/logout',
  path: '/api/auth/github/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubPreviewAuthorizeRoute =
  ApiAuthGithubPreviewAuthorizeRouteImport.update({
    id: '/api/auth/github/preview-authorize',
    path: '/api/auth/github/preview-authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGithubPreviewCallbackRoute =
  ApiAuthGithubPreviewCallbackRouteImport.update({
    id: '/api/auth/github/preview-callback',
    path: '/api/auth/github/preview-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGithubPreviewRedeemRoute =
  ApiAuthGithubPreviewRedeemRouteImport.update({
    id: '/api/auth/github/preview-redeem',
    path: '/api/auth/github/preview-redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGithubPreviewStartRoute =
  ApiAuthGithubPreviewStartRouteImport.update({
    id: '/api/auth/github/preview-start',
    path: '/api/auth/github/preview-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGithubSessionRoute = ApiAuthGithubSessionRouteImport.update({
  id: '/api/auth/github/session',
  path: '/api/auth/github/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diffs': typeof DiffsRouteRouteWithChildren
  '/bugs': typeof BugsRoute
  '/diag/$': typeof DiagSplatRoute
  '/diffs/$': typeof DiffsSplatRoute
  '/diffs/': typeof DiffsIndexRoute
  '/api/diffs/diff': typeof ApiDiffsDiffRoute
  '/api/diffs/entity-diff': typeof ApiDiffsEntityDiffRoute
  '/api/diffs/github-diff-file': typeof ApiDiffsGithubDiffFileRoute
  '/api/diffs/pull-requests': typeof ApiDiffsPullRequestsRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/github/config': typeof ApiAuthGithubConfigRoute
  '/api/auth/github/installations': typeof ApiAuthGithubInstallationsRoute
  '/api/auth/github/login': typeof ApiAuthGithubLoginRoute
  '/api/auth/github/logout': typeof ApiAuthGithubLogoutRoute
  '/api/auth/github/preview-authorize': typeof ApiAuthGithubPreviewAuthorizeRoute
  '/api/auth/github/preview-callback': typeof ApiAuthGithubPreviewCallbackRoute
  '/api/auth/github/preview-redeem': typeof ApiAuthGithubPreviewRedeemRoute
  '/api/auth/github/preview-start': typeof ApiAuthGithubPreviewStartRoute
  '/api/auth/github/session': typeof ApiAuthGithubSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/diag/$': typeof DiagSplatRoute
  '/diffs/$': typeof DiffsSplatRoute
  '/diffs': typeof DiffsIndexRoute
  '/api/diffs/diff': typeof ApiDiffsDiffRoute
  '/api/diffs/entity-diff': typeof ApiDiffsEntityDiffRoute
  '/api/diffs/github-diff-file': typeof ApiDiffsGithubDiffFileRoute
  '/api/diffs/pull-requests': typeof ApiDiffsPullRequestsRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/github/config': typeof ApiAuthGithubConfigRoute
  '/api/auth/github/installations': typeof ApiAuthGithubInstallationsRoute
  '/api/auth/github/login': typeof ApiAuthGithubLoginRoute
  '/api/auth/github/logout': typeof ApiAuthGithubLogoutRoute
  '/api/auth/github/preview-authorize': typeof ApiAuthGithubPreviewAuthorizeRoute
  '/api/auth/github/preview-callback': typeof ApiAuthGithubPreviewCallbackRoute
  '/api/auth/github/preview-redeem': typeof ApiAuthGithubPreviewRedeemRoute
  '/api/auth/github/preview-start': typeof ApiAuthGithubPreviewStartRoute
  '/api/auth/github/session': typeof ApiAuthGithubSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diffs': typeof DiffsRouteRouteWithChildren
  '/bugs': typeof BugsRoute
  '/diag/$': typeof DiagSplatRoute
  '/diffs/$': typeof DiffsSplatRoute
  '/diffs/': typeof DiffsIndexRoute
  '/api/diffs/diff': typeof ApiDiffsDiffRoute
  '/api/diffs/entity-diff': typeof ApiDiffsEntityDiffRoute
  '/api/diffs/github-diff-file': typeof ApiDiffsGithubDiffFileRoute
  '/api/diffs/pull-requests': typeof ApiDiffsPullRequestsRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/github/config': typeof ApiAuthGithubConfigRoute
  '/api/auth/github/installations': typeof ApiAuthGithubInstallationsRoute
  '/api/auth/github/login': typeof ApiAuthGithubLoginRoute
  '/api/auth/github/logout': typeof ApiAuthGithubLogoutRoute
  '/api/auth/github/preview-authorize': typeof ApiAuthGithubPreviewAuthorizeRoute
  '/api/auth/github/preview-callback': typeof ApiAuthGithubPreviewCallbackRoute
  '/api/auth/github/preview-redeem': typeof ApiAuthGithubPreviewRedeemRoute
  '/api/auth/github/preview-start': typeof ApiAuthGithubPreviewStartRoute
  '/api/auth/github/session': typeof ApiAuthGithubSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diffs'
    | '/bugs'
    | '/diag/$'
    | '/diffs/$'
    | '/diffs/'
    | '/api/diffs/diff'
    | '/api/diffs/entity-diff'
    | '/api/diffs/github-diff-file'
    | '/api/diffs/pull-requests'
    | '/api/auth/github/callback'
    | '/api/auth/github/config'
    | '/api/auth/github/installations'
    | '/api/auth/github/login'
    | '/api/auth/github/logout'
    | '/api/auth/github/preview-authorize'
    | '/api/auth/github/preview-callback'
    | '/api/auth/github/preview-redeem'
    | '/api/auth/github/preview-start'
    | '/api/auth/github/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bugs'
    | '/diag/$'
    | '/diffs/$'
    | '/diffs'
    | '/api/diffs/diff'
    | '/api/diffs/entity-diff'
    | '/api/diffs/github-diff-file'
    | '/api/diffs/pull-requests'
    | '/api/auth/github/callback'
    | '/api/auth/github/config'
    | '/api/auth/github/installations'
    | '/api/auth/github/login'
    | '/api/auth/github/logout'
    | '/api/auth/github/preview-authorize'
    | '/api/auth/github/preview-callback'
    | '/api/auth/github/preview-redeem'
    | '/api/auth/github/preview-start'
    | '/api/auth/github/session'
  id:
    | '__root__'
    | '/'
    | '/diffs'
    | '/bugs'
    | '/diag/$'
    | '/diffs/$'
    | '/diffs/'
    | '/api/diffs/diff'
    | '/api/diffs/entity-diff'
    | '/api/diffs/github-diff-file'
    | '/api/diffs/pull-requests'
    | '/api/auth/github/callback'
    | '/api/auth/github/config'
    | '/api/auth/github/installations'
    | '/api/auth/github/login'
    | '/api/auth/github/logout'
    | '/api/auth/github/preview-authorize'
    | '/api/auth/github/preview-callback'
    | '/api/auth/github/preview-redeem'
    | '/api/auth/github/preview-start'
    | '/api/auth/github/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffsRouteRoute: typeof DiffsRouteRouteWithChildren
  BugsRoute: typeof BugsRoute
  DiagSplatRoute: typeof DiagSplatRoute
  ApiDiffsDiffRoute: typeof ApiDiffsDiffRoute
  ApiDiffsEntityDiffRoute: typeof ApiDiffsEntityDiffRoute
  ApiDiffsGithubDiffFileRoute: typeof ApiDiffsGithubDiffFileRoute
  ApiDiffsPullRequestsRoute: typeof ApiDiffsPullRequestsRoute
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
  ApiAuthGithubConfigRoute: typeof ApiAuthGithubConfigRoute
  ApiAuthGithubInstallationsRoute: typeof ApiAuthGithubInstallationsRoute
  ApiAuthGithubLoginRoute: typeof ApiAuthGithubLoginRoute
  ApiAuthGithubLogoutRoute: typeof ApiAuthGithubLogoutRoute
  ApiAuthGithubPreviewAuthorizeRoute: typeof ApiAuthGithubPreviewAuthorizeRoute
  ApiAuthGithubPreviewCallbackRoute: typeof ApiAuthGithubPreviewCallbackRoute
  ApiAuthGithubPreviewRedeemRoute: typeof ApiAuthGithubPreviewRedeemRoute
  ApiAuthGithubPreviewStartRoute: typeof ApiAuthGithubPreviewStartRoute
  ApiAuthGithubSessionRoute: typeof ApiAuthGithubSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diffs': {
      id: '/diffs'
      path: '/diffs'
      fullPath: '/diffs'
      preLoaderRoute: typeof DiffsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag/$': {
      id: '/diag/$'
      path: '/diag/$'
      fullPath: '/diag/$'
      preLoaderRoute: typeof DiagSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diffs/': {
      id: '/diffs/'
      path: '/'
      fullPath: '/diffs/'
      preLoaderRoute: typeof DiffsIndexRouteImport
      parentRoute: typeof DiffsRouteRoute
    }
    '/diffs/$': {
      id: '/diffs/$'
      path: '/$'
      fullPath: '/diffs/$'
      preLoaderRoute: typeof DiffsSplatRouteImport
      parentRoute: typeof DiffsRouteRoute
    }
    '/api/diffs/diff': {
      id: '/api/diffs/diff'
      path: '/api/diffs/diff'
      fullPath: '/api/diffs/diff'
      preLoaderRoute: typeof ApiDiffsDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diffs/entity-diff': {
      id: '/api/diffs/entity-diff'
      path: '/api/diffs/entity-diff'
      fullPath: '/api/diffs/entity-diff'
      preLoaderRoute: typeof ApiDiffsEntityDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diffs/github-diff-file': {
      id: '/api/diffs/github-diff-file'
      path: '/api/diffs/github-diff-file'
      fullPath: '/api/diffs/github-diff-file'
      preLoaderRoute: typeof ApiDiffsGithubDiffFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diffs/pull-requests': {
      id: '/api/diffs/pull-requests'
      path: '/api/diffs/pull-requests'
      fullPath: '/api/diffs/pull-requests'
      preLoaderRoute: typeof ApiDiffsPullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/api/auth/github/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/config': {
      id: '/api/auth/github/config'
      path: '/api/auth/github/config'
      fullPath: '/api/auth/github/config'
      preLoaderRoute: typeof ApiAuthGithubConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/installations': {
      id: '/api/auth/github/installations'
      path: '/api/auth/github/installations'
      fullPath: '/api/auth/github/installations'
      preLoaderRoute: typeof ApiAuthGithubInstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/login': {
      id: '/api/auth/github/login'
      path: '/api/auth/github/login'
      fullPath: '/api/auth/github/login'
      preLoaderRoute: typeof ApiAuthGithubLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/logout': {
      id: '/api/auth/github/logout'
      path: '/api/auth/github/logout'
      fullPath: '/api/auth/github/logout'
      preLoaderRoute: typeof ApiAuthGithubLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/preview-authorize': {
      id: '/api/auth/github/preview-authorize'
      path: '/api/auth/github/preview-authorize'
      fullPath: '/api/auth/github/preview-authorize'
      preLoaderRoute: typeof ApiAuthGithubPreviewAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/preview-callback': {
      id: '/api/auth/github/preview-callback'
      path: '/api/auth/github/preview-callback'
      fullPath: '/api/auth/github/preview-callback'
      preLoaderRoute: typeof ApiAuthGithubPreviewCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/preview-redeem': {
      id: '/api/auth/github/preview-redeem'
      path: '/api/auth/github/preview-redeem'
      fullPath: '/api/auth/github/preview-redeem'
      preLoaderRoute: typeof ApiAuthGithubPreviewRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/preview-start': {
      id: '/api/auth/github/preview-start'
      path: '/api/auth/github/preview-start'
      fullPath: '/api/auth/github/preview-start'
      preLoaderRoute: typeof ApiAuthGithubPreviewStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/session': {
      id: '/api/auth/github/session'
      path: '/api/auth/github/session'
      fullPath: '/api/auth/github/session'
      preLoaderRoute: typeof ApiAuthGithubSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DiffsRouteRouteChildren {
  DiffsSplatRoute: typeof DiffsSplatRoute
  DiffsIndexRoute: typeof DiffsIndexRoute
}

const DiffsRouteRouteChildren: DiffsRouteRouteChildren = {
  DiffsSplatRoute: DiffsSplatRoute,
  DiffsIndexRoute: DiffsIndexRoute,
}

const DiffsRouteRouteWithChildren = DiffsRouteRoute._addFileChildren(
  DiffsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffsRouteRoute: DiffsRouteRouteWithChildren,
  BugsRoute: BugsRoute,
  DiagSplatRoute: DiagSplatRoute,
  ApiDiffsDiffRoute: ApiDiffsDiffRoute,
  ApiDiffsEntityDiffRoute: ApiDiffsEntityDiffRoute,
  ApiDiffsGithubDiffFileRoute: ApiDiffsGithubDiffFileRoute,
  ApiDiffsPullRequestsRoute: ApiDiffsPullRequestsRoute,
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
  ApiAuthGithubConfigRoute: ApiAuthGithubConfigRoute,
  ApiAuthGithubInstallationsRoute: ApiAuthGithubInstallationsRoute,
  ApiAuthGithubLoginRoute: ApiAuthGithubLoginRoute,
  ApiAuthGithubLogoutRoute: ApiAuthGithubLogoutRoute,
  ApiAuthGithubPreviewAuthorizeRoute: ApiAuthGithubPreviewAuthorizeRoute,
  ApiAuthGithubPreviewCallbackRoute: ApiAuthGithubPreviewCallbackRoute,
  ApiAuthGithubPreviewRedeemRoute: ApiAuthGithubPreviewRedeemRoute,
  ApiAuthGithubPreviewStartRoute: ApiAuthGithubPreviewStartRoute,
  ApiAuthGithubSessionRoute: ApiAuthGithubSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
