/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsHandleRouteImport } from './routes/products/$handle'
import { Route as PoliciesShippingRouteImport } from './routes/policies/shipping'
import { Route as PoliciesReturnsRouteImport } from './routes/policies/returns'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies/privacy'
import { Route as DiagSplatRouteImport } from './routes/diag/$'

const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesShippingRoute = PoliciesShippingRouteImport.update({
  id: '/policies/shipping',
  path: '/policies/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesReturnsRoute = PoliciesReturnsRouteImport.update({
  id: '/policies/returns',
  path: '/policies/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagSplatRoute = DiagSplatRouteImport.update({
  id: '/diag/$',
  path: '/diag/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bugs': typeof BugsRoute
  '/cart': typeof CartRoute
  '/commissions': typeof CommissionsRoute
  '/diag/$': typeof DiagSplatRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bugs': typeof BugsRoute
  '/cart': typeof CartRoute
  '/commissions': typeof CommissionsRoute
  '/diag/$': typeof DiagSplatRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bugs': typeof BugsRoute
  '/cart': typeof CartRoute
  '/commissions': typeof CommissionsRoute
  '/diag/$': typeof DiagSplatRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bugs'
    | '/cart'
    | '/commissions'
    | '/diag/$'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/shipping'
    | '/products/$handle'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bugs'
    | '/cart'
    | '/commissions'
    | '/diag/$'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/shipping'
    | '/products/$handle'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bugs'
    | '/cart'
    | '/commissions'
    | '/diag/$'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/shipping'
    | '/products/$handle'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BugsRoute: typeof BugsRoute
  CartRoute: typeof CartRoute
  CommissionsRoute: typeof CommissionsRoute
  DiagSplatRoute: typeof DiagSplatRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesReturnsRoute: typeof PoliciesReturnsRoute
  PoliciesShippingRoute: typeof PoliciesShippingRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/shipping': {
      id: '/policies/shipping'
      path: '/policies/shipping'
      fullPath: '/policies/shipping'
      preLoaderRoute: typeof PoliciesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/returns': {
      id: '/policies/returns'
      path: '/policies/returns'
      fullPath: '/policies/returns'
      preLoaderRoute: typeof PoliciesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag/$': {
      id: '/diag/$'
      path: '/diag/$'
      fullPath: '/diag/$'
      preLoaderRoute: typeof DiagSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BugsRoute: BugsRoute,
  CartRoute: CartRoute,
  CommissionsRoute: CommissionsRoute,
  DiagSplatRoute: DiagSplatRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesReturnsRoute: PoliciesReturnsRoute,
  PoliciesShippingRoute: PoliciesShippingRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
