/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagSplatRouteImport } from './routes/diag/$'

const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagSplatRoute = DiagSplatRouteImport.update({
  id: '/diag/$',
  path: '/diag/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/diag/$': typeof DiagSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/diag/$': typeof DiagSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/diag/$': typeof DiagSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bugs' | '/diag/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bugs' | '/diag/$'
  id: '__root__' | '/' | '/bugs' | '/diag/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BugsRoute: typeof BugsRoute
  DiagSplatRoute: typeof DiagSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag/$': {
      id: '/diag/$'
      path: '/diag/$'
      fullPath: '/diag/$'
      preLoaderRoute: typeof DiagSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BugsRoute: BugsRoute,
  DiagSplatRoute: DiagSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
