import {fileURLToPath} from 'node:url'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2026-06-01',
  modules: ['@nuxtjs/color-mode'],
  // Repo-wide theme contract (docs/projects/theme-switcher-unification/plan.md):
  // tri-state light/dark/system, localStorage key 'theme', no-flash pre-paint
  // application. v4 defaults already give a bare .dark/.light class on <html>
  // (classPrefix/classSuffix ''), matching Panda's built-in _dark (.dark &)
  // condition -- left unset rather than restated.
  colorMode: {
    preference: 'system',
    fallback: 'light',
    storageKey: 'theme',
    disableTransition: true,
  },
  // Deploy as a Cloudflare Worker (module syntax) via Nitro.
  nitro: {
    preset: 'cloudflare_module',
  },
  // Public observability config, baked at build from the NUXT_PUBLIC_SENTRY_DSN /
  // NUXT_PUBLIC_POSTHOG_KEY build env (the deploy workflow sets them from repo
  // variables -- the same source as every other app's client build). Empty until
  // set, so the app runs uninstrumented; no runtime worker var. The client plugin
  // (app/plugins/observability.client.ts) reads these.
  runtimeConfig: {
    public: {
      sentryDsn: process.env.NUXT_PUBLIC_SENTRY_DSN ?? '',
      posthogKey: process.env.NUXT_PUBLIC_POSTHOG_KEY ?? '',
    },
  },
  // PandaCSS: codegen output lives in styled-system/ (gitignored, regenerated by
  // the prepare script). The alias makes both Vite and vue-tsc resolve it.
  alias: {
    'styled-system': fileURLToPath(new URL('./styled-system', import.meta.url)),
  },
  css: ['~/assets/css/global.css'],
  postcss: {
    plugins: {
      '@pandacss/dev/postcss': {},
    },
  },
})
