import {fileURLToPath} from 'node:url'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2026-06-01',
  // Deploy as a Cloudflare Worker (module syntax) via Nitro.
  nitro: {
    preset: 'cloudflare_module',
  },
  // PandaCSS: codegen output lives in styled-system/ (gitignored, regenerated by
  // the prepare script). The alias makes both Vite and vue-tsc resolve it.
  alias: {
    'styled-system': fileURLToPath(new URL('./styled-system', import.meta.url)),
  },
  css: ['~/assets/css/global.css'],
  postcss: {
    plugins: {
      '@pandacss/dev/postcss': {},
    },
  },
})
