import {fileURLToPath} from 'node:url'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2026-06-01',
  // Deploy as a Cloudflare Worker (module syntax) via Nitro.
  nitro: {
    preset: 'cloudflare_module',
  },
  // Client observability config, exposed to the browser. Populated at runtime
  // from NUXT_PUBLIC_* env vars; empty defaults keep Sentry/PostHog off until
  // credentials are provided (see app/plugins/observability.client.ts).
  runtimeConfig: {
    public: {
      sentryDsn: '',
      posthogKey: '',
      posthogHost: '',
    },
  },
  // PandaCSS: codegen output lives in styled-system/ (gitignored, regenerated by
  // the prepare script). The alias makes both Vite and vue-tsc resolve it.
  alias: {
    'styled-system': fileURLToPath(new URL('./styled-system', import.meta.url)),
  },
  css: ['~/assets/css/global.css'],
  postcss: {
    plugins: {
      '@pandacss/dev/postcss': {},
    },
  },
})
