name: CD Deploy onvibes.org

on:
  push:
    branches: [main]
    paths:
      - 'apps/onvibes.org/**'
      - '.github/workflows/cd-deploy-onvibes-org.yml'

defaults:
  run:
    working-directory: apps/onvibes.org

jobs:
  deploy:
    name: wrangler deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: mise
        uses: ./.github/actions/setup-mise

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: panda codegen
        run: pnpm exec panda codegen

      - name: astro build
        env:
          PUBLIC_SENTRY_DSN: ${{ vars.SENTRY_DSN_ONVIBES_ORG }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT_ONVIBES_ORG }}
          PUBLIC_POSTHOG_KEY: ${{ vars.POSTHOG_KEY_ONVIBES_ORG }}
        run: pnpm exec astro build

      - name: wrangler deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy -c dist/server/wrangler.json
          workingDirectory: apps/onvibes.org
