/**
 * Behavioral spot-check source for @std/collections parts, shared by the
 * emit-time verifier (bin/decompose.ts) and the registry verifier
 * (bin/verify-registry.ts). aggregate-groups exercises a rewritten cross-part
 * import (it depends on the map-entries part); chunk exercises a standalone
 * part.
 */
export function behaviorCheckScript(scope: string): string {
  return `// Generated by pkg.dog spike -- behavioral spot-check for @std/collections parts.
import {aggregateGroups} from '${scope}/std__collections__aggregate-groups'
import {chunk} from '${scope}/std__collections__chunk'

const chunked = JSON.stringify(chunk([1, 2, 3, 4, 5], 2))
if (chunked !== '[[1,2],[3,4],[5]]') throw new Error(\`chunk misbehaved: \${chunked}\`)

const aggregated = JSON.stringify(
  aggregateGroups({a: [1, 2], b: [3]}, (current: number, _key, _first, acc?: number) =>
    (acc ?? 0) + current,
  ),
)
if (aggregated !== '{"a":3,"b":3}') throw new Error(\`aggregateGroups misbehaved: \${aggregated}\`)
console.log('behavior spot-checks passed (chunk, aggregateGroups via cross-part dep)')
`
}
