import {cp, mkdir, rm} from 'node:fs/promises'
import {dirname, join} from 'node:path'
import {pathToFileURL} from 'node:url'
import type {EmittedPart} from './emit.ts'
import type {UpstreamPackage} from './registry.ts'

export interface VerifyFailure {
  specifier: string
  reason: string
}

/**
 * Prove the emitted parts are installable and equivalent: copy every part
 * into a throwaway consumer's node_modules (npm-less install), then import
 * each published specifier in a child process and compare its export names
 * and types against the upstream module. Cross-part dependencies resolve
 * through the same node_modules, so rewritten imports are exercised too.
 */
export async function verifyParts(
  emitted: EmittedPart[],
  upstream: UpstreamPackage,
  verifyDir: string,
): Promise<VerifyFailure[]> {
  await rm(verifyDir, {recursive: true, force: true})
  await mkdir(verifyDir, {recursive: true})
  await Bun.write(
    join(verifyDir, 'package.json'),
    `${JSON.stringify({name: 'pkgdog-verify-consumer', private: true, type: 'module'}, null, 2)}\n`,
  )
  for (const {part, dir} of emitted) {
    const installPath = join(verifyDir, 'node_modules', part.name)
    await mkdir(dirname(installPath), {recursive: true})
    await cp(dir, installPath, {recursive: true})
  }

  const entries: {specifier: string; expectedKeys: string[]; expectedTypes: string[]}[] = []
  for (const {part} of emitted) {
    for (const [subpath, entry] of Object.entries(part.exportsMap)) {
      const specifier = subpath === '.' ? part.name : `${part.name}${subpath.slice(1)}`
      const upstreamModule = (await import(
        pathToFileURL(join(upstream.dir, entry.runtime)).href
      )) as Record<string, unknown>
      const expectedKeys = Object.keys(upstreamModule).sort((a, b) => a.localeCompare(b, 'en'))
      entries.push({
        specifier,
        expectedKeys,
        expectedTypes: expectedKeys.map((k) => typeof upstreamModule[k]),
      })
    }
  }
  await Bun.write(join(verifyDir, 'manifest.json'), JSON.stringify({entries}, null, 2))
  await Bun.write(join(verifyDir, 'check.ts'), CHECK_SCRIPT)

  const child = Bun.spawn(['bun', 'check.ts'], {
    cwd: verifyDir,
    stdout: 'pipe',
    stderr: 'pipe',
    timeout: 120_000,
  })
  const [stdout, stderr] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ])
  if ((await child.exited) !== 0 && stdout.trim() === '') {
    return [{specifier: '(check script)', reason: stderr.trim() || 'no output (timed out?)'}]
  }
  try {
    return (JSON.parse(stdout) as {failures: VerifyFailure[]}).failures
  } catch {
    return [{specifier: '(check script)', reason: `unparseable output: ${stdout.slice(0, 200)}`}]
  }
}

const CHECK_SCRIPT = `// Generated by pkg.dog spike -- imports each part and compares to the manifest.
interface Entry {
  specifier: string
  expectedKeys: string[]
  expectedTypes: string[]
}
const manifest = (await Bun.file(new URL('manifest.json', import.meta.url)).json()) as {
  entries: Entry[]
}
const failures: {specifier: string; reason: string}[] = []
for (const {specifier, expectedKeys, expectedTypes} of manifest.entries) {
  try {
    const mod = (await import(specifier)) as Record<string, unknown>
    const keys = Object.keys(mod).sort((a, b) => a.localeCompare(b, 'en'))
    const types = keys.map((k) => typeof mod[k])
    if (JSON.stringify(keys) !== JSON.stringify(expectedKeys)) {
      failures.push({specifier, reason: \`export keys \${keys.join()} != \${expectedKeys.join()}\`})
    } else if (JSON.stringify(types) !== JSON.stringify(expectedTypes)) {
      failures.push({specifier, reason: \`export types \${types.join()} != \${expectedTypes.join()}\`})
    }
  } catch (error) {
    failures.push({specifier, reason: String(error)})
  }
}
console.log(JSON.stringify({failures}))
`
